export const SIGNUP_SUCCESSFULLY = "SIGNUP_SUCCESSFULLY";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGEDIN_SUCCESSFULLY = "LOGEDIN_SUCCESSFULLY";
export const LOGEDIN_FAILURE = "LOGEDIN_FAILURE";

export const PRODUCT_ADD_SUCCESSFULLY = "PRODUCT_ADD_SUCCESSFULLY";
export const PRODUCT_ADD_FAILURE = "PRODUCT_ADD_FAILURE";
export const PRODUCT_FETCH_SUCCESSFULLY = "PRODUCT_FETCH_SUCCESSFULLY";
export const PRODUCT_FETCH_FAILURE = "PRODUCT_FETCH_FAILURE";

export const PRODUCT_UPDATE_SUCCESSFULLY = "PRODUCT_UPDATE_SUCCESSFULLY";
export const PRODUCT_UPDATE_FAILURE = "PRODUCT_UPDATE_FAILURE";
export const PRODUCT_DELETE_SUCCESSFULLY = "PRODUCT_DELETE_SUCCESSFULLY";
export const PRODUCT_DELETE_FAILURE = "PRODUCT_DELETE_FAILURE";

export const PRODUCT_FETCH_BYID_SUCCESSFULLY = "PRODUCT_FETCH_BYID_SUCCESSFULLY";
export const PRODUCT_FETCH_BYID_FAILURE = "PRODUCT_FETCH_BYID_FAILURE";

export const PRODUCT_SEARCH_SUCCESSFULLY = "PRODUCT_SEARCH_SUCCESSFULLY";
export const PRODUCT_SEARCH_FAILURE = "PRODUCT_SEARCH_FAILURE";