export const SIGNUP_SUCCESSFULLY = "SIGNUP_SUCCESSFULLY";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGEDIN_SUCCESSFULLY = "LOGEDIN_SUCCESSFULLY";
export const LOGEDIN_FAILURE = "LOGEDIN_FAILURE";

export const PRODUCT_ADD_SUCCESSFULLY = "PRODUCT_ADD_SUCCESSFULLY";
export const PRODUCT_ADD_FAILURE = "PRODUCT_ADD_FAILURE";

export const PRODUCT_FETCH_SUCCESSFULLY = "PRODUCT_FETCH_SUCCESSFULLY";
export const PRODUCT_FETCH_FAILURE = "PRODUCT_FETCH_FAILURE";

export const PRODUCT_UPDATE_SUCCESSFULLY = "PRODUCT_UPDATE_SUCCESSFULLY";
export const PRODUCT_UPDATE_FAILURE = "PRODUCT_UPDATE_FAILURE";
